# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lisa Learns to Code
email: lcarter347@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a computer information systems major interested in web and app dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lcarter347.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  lcarter347

# Build settings
markdown: kramdown

